"""Comprehensive test suite for Onshape MCP tooling.

Tests all API methods against a real Onshape account. Creates a temporary
test document, exercises features, and cleans up afterward.

Usage:
  python test_api.py              # Run all tests
  python test_api.py --keep       # Keep test document after run (for inspection)
  python test_api.py --verbose    # Show detailed API responses
  python test_api.py --test NAME  # Run a single test by name

Tests:
  1. Connection          — Verify API credentials work
  2. Create document     — Create a new document
  3. List elements       — List Part Studios in the new document
  4. Add sketch circle   — Add a circle sketch feature
  5. Add extrude         — Extrude the circle into a cylinder
  6. Get features        — Verify features were added
  7. Get parts           — Verify part was created
  8. Create cylinder     — High-level cylinder helper
  9. Add sketch rect     — Add a rectangle sketch
  10. Materials          — List materials from library
  11. Set material       — Set material on a part
  12. Create drawing     — Create a drawing from template
  13. Search documents   — Search for the test document
  14. Delete feature     — Delete a feature
  15. Delete document    — Clean up test document
"""

import sys
import time
import argparse
import traceback
from dataclasses import dataclass, field

from onshape_api import OnshapeClient


@dataclass
class TestContext:
    """Shared state across tests."""
    client: OnshapeClient = field(default_factory=OnshapeClient)
    document_id: str = ""
    workspace_id: str = ""
    element_id: str = ""  # Part Studio
    sketch_feature_id: str = ""
    extrude_feature_id: str = ""
    cylinder_sketch_fid: str = ""
    cylinder_extrude_fid: str = ""
    part_id: str = ""
    keep: bool = False
    verbose: bool = False


@dataclass
class TestResult:
    name: str
    passed: bool
    message: str = ""
    duration: float = 0.0


def run_test(ctx: TestContext, name: str, func) -> TestResult:
    """Run a single test function and capture result."""
    start = time.time()
    try:
        msg = func(ctx)
        duration = time.time() - start
        return TestResult(name=name, passed=True, message=msg or "OK",
                          duration=duration)
    except Exception as e:
        duration = time.time() - start
        tb = traceback.format_exc() if ctx.verbose else str(e)
        return TestResult(name=name, passed=False, message=tb,
                          duration=duration)


# ── Individual Tests ─────────────────────────────────────────────────────

def test_connection(ctx: TestContext) -> str:
    """Test API connectivity."""
    assert ctx.client.auth[0], "ONSHAPE_ACCESS_KEY not set"
    assert ctx.client.auth[1], "ONSHAPE_SECRET_KEY not set"
    # Try a lightweight call
    result = ctx.client.search_documents("test", limit=1)
    assert "items" in result, f"Unexpected response: {list(result.keys())}"
    return f"Connected to {ctx.client.base_url}"


def test_create_document(ctx: TestContext) -> str:
    """Create a test document."""
    result = ctx.client.create_document(
        name="MCP-Test-AutoGenerated",
        description="Automated test — safe to delete",
    )
    ctx.document_id = result["document_id"]
    ctx.workspace_id = result["workspace_id"]
    ctx.element_id = result["element_id"]
    assert ctx.document_id, "No document_id returned"
    assert ctx.workspace_id, "No workspace_id returned"
    assert ctx.element_id, "No element_id (Part Studio) returned"
    return f"Created doc {ctx.document_id}"


def test_list_elements(ctx: TestContext) -> str:
    """List elements in the new document."""
    elements = ctx.client.get_elements(ctx.document_id, ctx.workspace_id)
    part_studios = [e for e in elements if e["elementType"] == "PARTSTUDIO"]
    assert len(part_studios) >= 1, "No Part Studio found"
    return f"{len(elements)} elements ({len(part_studios)} Part Studios)"


def test_add_sketch_circle(ctx: TestContext) -> str:
    """Add a circle sketch to the Part Studio."""
    sketch = ctx.client.build_sketch_circle(
        name="Test Circle",
        plane="Top",
        radius_mm=15.0,
        center_x_mm=0.0,
        center_y_mm=0.0,
    )
    result = ctx.client.add_feature(
        ctx.document_id, ctx.workspace_id, ctx.element_id, sketch
    )
    state = result.get("featureState", {})
    assert state.get("featureStatus") == "OK", f"Sketch failed: {state}"
    ctx.sketch_feature_id = result["feature"]["featureId"]
    return f"Sketch featureId={ctx.sketch_feature_id}"


def test_add_extrude(ctx: TestContext) -> str:
    """Extrude the circle sketch."""
    extrude = ctx.client.build_extrude(
        sketch_feature_id=ctx.sketch_feature_id,
        depth_mm=50.0,
        name="Test Extrude",
    )
    result = ctx.client.add_feature(
        ctx.document_id, ctx.workspace_id, ctx.element_id, extrude
    )
    state = result.get("featureState", {})
    assert state.get("featureStatus") == "OK", f"Extrude failed: {state}"
    ctx.extrude_feature_id = result["feature"]["featureId"]
    return f"Extrude featureId={ctx.extrude_feature_id}"


def test_get_features(ctx: TestContext) -> str:
    """Verify features appear in the feature tree."""
    result = ctx.client.get_features(ctx.document_id, ctx.workspace_id,
                                     ctx.element_id)
    features = result.get("features", [])
    names = [f.get("name") for f in features]
    assert "Test Circle" in names, f"Sketch not found in: {names}"
    assert "Test Extrude" in names, f"Extrude not found in: {names}"
    return f"{len(features)} features: {names}"


def test_get_parts(ctx: TestContext) -> str:
    """Verify a part was created from the extrude."""
    parts = ctx.client.get_parts(ctx.document_id, ctx.workspace_id,
                                 ctx.element_id)
    assert len(parts) >= 1, "No parts found after extrude"
    ctx.part_id = parts[0].get("partId", "")
    name = parts[0].get("name", "?")
    return f"{len(parts)} part(s), first: {name} (partId={ctx.part_id})"


def test_create_cylinder(ctx: TestContext) -> str:
    """Test the high-level create_cylinder helper."""
    result = ctx.client.create_cylinder(
        ctx.document_id, ctx.workspace_id, ctx.element_id,
        diameter_mm=20.0, height_mm=30.0,
    )
    s_state = result["sketch"]["state"].get("featureStatus")
    e_state = result["extrude"]["state"].get("featureStatus")
    assert s_state == "OK", f"Cylinder sketch failed: {s_state}"
    assert e_state == "OK", f"Cylinder extrude failed: {e_state}"
    ctx.cylinder_sketch_fid = result["sketch"]["featureId"]
    ctx.cylinder_extrude_fid = result["extrude"]["featureId"]
    return f"Cylinder OK (sketch={ctx.cylinder_sketch_fid}, extrude={ctx.cylinder_extrude_fid})"


def test_add_sketch_rectangle(ctx: TestContext) -> str:
    """Add a rectangle sketch to the Part Studio."""
    sketch = ctx.client.build_sketch_rectangle(
        name="Test Rectangle",
        plane="Front",
        width_mm=40.0,
        height_mm=25.0,
    )
    result = ctx.client.add_feature(
        ctx.document_id, ctx.workspace_id, ctx.element_id, sketch
    )
    state = result.get("featureState", {})
    assert state.get("featureStatus") == "OK", f"Rectangle sketch failed: {state}"
    return f"Rectangle featureId={result['feature']['featureId']}"


def test_list_materials(ctx: TestContext) -> str:
    """List materials from the Onshape library."""
    materials = ctx.client.get_material_library()
    assert len(materials) > 0, "No materials returned"
    names = [m["displayName"] for m in materials[:5]]
    return f"{len(materials)} materials. Sample: {names}"


def test_set_material(ctx: TestContext) -> str:
    """Set material on a part."""
    assert ctx.part_id, "No part_id available from test_get_parts"
    result = ctx.client.set_part_material(
        ctx.document_id, ctx.workspace_id, ctx.element_id,
        ctx.part_id, "PLA",
    )
    assert result.get("status") == "SUCCEEDED", f"Set material failed: {result}"
    return "Material set to PLA"


def test_create_drawing(ctx: TestContext) -> str:
    """Create a drawing from MEMSYS template."""
    result = ctx.client.create_drawing(
        ctx.document_id, ctx.workspace_id,
        "Test Drawing",
        part_element_id=ctx.element_id,
        part_id=ctx.part_id,
        template_key="A3",
    )
    drawing_id = result.get("id")
    assert drawing_id, f"No drawing ID returned: {result}"
    return f"Drawing created: {drawing_id}"


def test_search_documents(ctx: TestContext) -> str:
    """Search for the test document."""
    result = ctx.client.search_documents("MCP-Test-AutoGenerated", limit=5)
    items = result.get("items", [])
    found = any(i.get("id") == ctx.document_id for i in items)
    return f"Found {len(items)} results, test doc present: {found}"


def test_delete_feature(ctx: TestContext) -> str:
    """Delete the cylinder extrude feature."""
    assert ctx.cylinder_extrude_fid, "No cylinder extrude featureId"
    ctx.client.delete_feature(
        ctx.document_id, ctx.workspace_id, ctx.element_id,
        ctx.cylinder_extrude_fid,
    )
    # Verify it's gone
    result = ctx.client.get_features(ctx.document_id, ctx.workspace_id,
                                     ctx.element_id)
    fids = [f.get("featureId") for f in result.get("features", [])]
    assert ctx.cylinder_extrude_fid not in fids, "Feature still present after delete"
    return f"Deleted {ctx.cylinder_extrude_fid}"


def test_delete_document(ctx: TestContext) -> str:
    """Delete the test document (cleanup)."""
    if ctx.keep:
        return f"SKIPPED (--keep flag). Doc: {ctx.document_id}"
    try:
        ctx.client.delete_document(ctx.document_id)
        return f"Deleted doc {ctx.document_id}"
    except PermissionError as e:
        return f"SKIPPED (no delete permission on API key). Doc: {ctx.document_id} — delete it manually."


# ── Test Registry ────────────────────────────────────────────────────────

ALL_TESTS = [
    ("Connection", test_connection),
    ("Create document", test_create_document),
    ("List elements", test_list_elements),
    ("Add sketch circle", test_add_sketch_circle),
    ("Add extrude", test_add_extrude),
    ("Get features", test_get_features),
    ("Get parts", test_get_parts),
    ("Create cylinder", test_create_cylinder),
    ("Add sketch rectangle", test_add_sketch_rectangle),
    ("Materials list", test_list_materials),
    ("Set material", test_set_material),
    ("Create drawing", test_create_drawing),
    ("Search documents", test_search_documents),
    ("Delete feature", test_delete_feature),
    ("Delete document", test_delete_document),
]


def main():
    parser = argparse.ArgumentParser(description="Test Onshape MCP API methods")
    parser.add_argument("--keep", action="store_true",
                        help="Keep test document after run (for manual inspection)")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Show detailed API responses and tracebacks")
    parser.add_argument("--test", "-t", type=str,
                        help="Run a single test by name (substring match)")
    args = parser.parse_args()

    ctx = TestContext(keep=args.keep, verbose=args.verbose)

    tests = ALL_TESTS
    if args.test:
        tests = [(n, f) for n, f in ALL_TESTS
                 if args.test.lower() in n.lower()]
        if not tests:
            print(f"No test matching '{args.test}'")
            print("Available tests:")
            for name, _ in ALL_TESTS:
                print(f"  {name}")
            sys.exit(1)

    print(f"\n{'='*60}")
    print(f" Onshape MCP API Test Suite")
    print(f" Tests: {len(tests)} | Keep: {args.keep}")
    print(f"{'='*60}\n")

    results: list[TestResult] = []
    for i, (name, func) in enumerate(tests, 1):
        print(f"  [{i:2d}/{len(tests)}] {name}...", end=" ", flush=True)
        result = run_test(ctx, name, func)
        results.append(result)

        status = "PASS" if result.passed else "FAIL"
        print(f"{status} ({result.duration:.1f}s) — {result.message}")

        # If a critical test fails, stop (can't continue without doc/sketch)
        if not result.passed and name in ("Connection", "Create document",
                                           "Add sketch circle"):
            print(f"\n  CRITICAL: '{name}' failed. Stopping.")
            break

    # ── Summary ──────────────────────────────────────────────────────────
    passed = sum(1 for r in results if r.passed)
    failed = sum(1 for r in results if not r.passed)
    total_time = sum(r.duration for r in results)

    print(f"\n{'='*60}")
    print(f" Results: {passed} passed, {failed} failed, {len(results)} total")
    print(f" Duration: {total_time:.1f}s")

    if ctx.keep and ctx.document_id:
        print(f" Test doc: {ctx.client.base_url}/documents/{ctx.document_id}")

    if failed:
        print(f"\n FAILED tests:")
        for r in results:
            if not r.passed:
                print(f"   - {r.name}: {r.message}")

    print(f"{'='*60}\n")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
